// Generated by CoffeeScript 1.6.3
var check, checker, minimatch;

minimatch = require('minimatch');

check = function(criteria, string) {
  if ('[object Array]' !== toString.call(criteria)) {
    criteria = [criteria];
  }
  return criteria.some(function(criterion) {
    switch (toString.call(criterion)) {
      case '[object String]':
        return string === criterion || minimatch(string, criterion);
      case '[object RegExp]':
        return criterion.test(string);
      case '[object Function]':
        return criterion(string);
    }
  });
};

check.checker = checker = function(criteria) {
  return check.bind(null, criteria);
};

module.exports = check;
