// Generated by CoffeeScript 1.6.3
var check, checker, exports, sort;

check = function(criteria, string) {};

checker = function(criteria) {
  return check.bind(this, criteria);
};

sort = function(criteria, list) {};

exports = {
  checker: checker,
  check: check,
  sort: sort
};
