// Generated by CoffeeScript 1.6.3
var anymatch, minimatch;

minimatch = require('minimatch');

anymatch = function(criteria, string, returnIndex) {
  var matchIndex, matched;
  if ('[object Array]' !== toString.call(criteria)) {
    criteria = [criteria];
  }
  matchIndex = -1;
  matched = criteria.some(function(criterion, index) {
    var result;
    result = (function() {
      switch (toString.call(criterion)) {
        case '[object String]':
          return string === criterion || minimatch(string, criterion);
        case '[object RegExp]':
          return criterion.test(string);
        case '[object Function]':
          return criterion(string);
        default:
          return false;
      }
    })();
    if (result) {
      matchIndex = index;
    }
    return result;
  });
  if (returnIndex === true) {
    return matchIndex;
  } else {
    return matched;
  }
};

anymatch.matcher = function(criteria) {
  return anymatch.bind(null, criteria);
};

module.exports = anymatch;
